# Generated by Django 6.0 on 2026-01-04 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
        ("users", "0002_alter_customuser_options_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(auto_now_add=True, verbose_name="Дата оплаты")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты")),
                (
                    "type_payment",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("on_line", "Перевод на счет")],
                        default=None,
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "object_payment",
                    models.CharField(
                        choices=[("course", "Курс"), ("lesson", "Урок")],
                        max_length=20,
                        verbose_name="Тип объекта оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_object",
                        to="study.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_object",
                        to="study.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ("-payment_date",),
            },
        ),
    ]
