# Generated by Django 6.0 on 2026-01-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_object",
                to="study.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_object",
                to="study.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
