# Generated by Django 6.0 on 2026-01-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_course_alter_payments_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="object_payment",
        ),
    ]
