# Generated by Django 6.0 on 2026-01-12 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="type_payment",
            new_name="payment_method",
        ),
        migrations.AddField(
            model_name="payments",
            name="object_payment",
            field=models.CharField(
                choices=[("course", "Курс"), ("lesson", "Урок")],
                default=3,
                max_length=10,
                verbose_name="Тип объекта оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
