# Generated by Django 6.0 on 2026-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_type_payment_payments_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="pyment_link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=600,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID сессии", max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
