# Generated by Django 5.2.10 on 2026-01-14 15:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payments_pyment_link_payments_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.TimeField(
                default=datetime.datetime(2026, 1, 14, 15, 16, 4, 217321, tzinfo=datetime.timezone.utc),
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
