# Generated by Django 5.2.10 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_subscription_created_at_subscription_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.TimeField(auto_now=True, verbose_name="Дата последнего обновления"),
        ),
    ]
