version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/stage5
      - static_volume:/stage5/static
      - media_volume:/stage5/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - HOST=postgres
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  static_volume:
  media_volume:
