# Generated by Django 5.2.10 on 2026-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
