name: Stage5 CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependence
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-root

      - name: Setup environment for TCP connection
        run: |
          echo "SECRET_KEY=django-insecure-test-$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=config.settings" >> $GITHUB_ENV          
          echo "DB_ENGINE=django.db.backends.postgresql" >> $GITHUB_ENV
          echo "DB_NAME=test_db" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV  # Важно: localhost для TCP
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Run Django commands
        run: |
          sleep 5
          poetry run python manage.py migrate --noinput
          poetry run python manage.py test